# Generated by Django 2.0.6 on 2018-10-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=255)),
                ('ementa', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField(max_length=255)),
                ('ano', models.TextField(max_length=255)),
                ('semestre', models.TextField(max_length=255)),
                ('turma', models.TextField(max_length=255)),
                ('professor', models.TextField(max_length=255)),
                ('disciplina', models.TextField(max_length=255)),
            ],
        ),
    ]
